on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C3
    outputs:
     stylegan2:
        type: volume
    uses: git-checkout@v1
    with:
      # url: https://github.com/gradient-ai/stylegan2.git
      url: context.event.github.url
      ref: context.event.github.ref
  StyleGan2:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      stylegan2: CloneRepo.outputs.stylegan2
    outputs:
      generatedFaces:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        pip install scipy==1.3.3
        pip install requests==2.22.0
        pip install Pillow==6.2.1
        cd /inputs/stylegan2
        curl -fsSL https://code-server.dev/install.sh | sh &> /dev/null
        apt-get install screen &> /dev/null
        apt-get install --yes git ssh python3-venv &> /dev/null
        wget -q -c -nc https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip -qq -n ngrok-stable-linux-amd64.zip
        get_ipython().system_raw('./ngrok http 8888 &')
        sleep 3
        import requests
        from re import sub
        r = requests.get('http://localhost:4040/api/tunnels')
        str_ssh = r.json()['tunnels'][0]['public_url']
        print(str_ssh)
        code-server --bind-addr 127.0.0.1:8888 --auth none &
        python run_generator.py generate-images \
          --network=gdrive:networks/stylegan2-ffhq-config-f.pkl \
          --seeds=6600-6605 \
          --truncation-psi=0.5 \
          --result-dir=/outputs/generatedFaces
      image: tensorflow/tensorflow:1.14.0-gpu-py3
